# Generated by Django 5.0.14 on 2026-08-31 14:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("address", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "name"],
                        name="customers_c_organiz_484379_idx",
                    ),
                    models.Index(
                        fields=["organization", "email"],
                        name="customers_c_organiz_d03b43_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                check=models.Q(("name", ""), _negated=True),
                name="customer_name_not_empty",
            ),
        ),
    ]
